from __future__ import annotations

# indicator_keys.py — single source of truth cho tất cả threshold
BOLLINGER_SQUEEZE_THRESHOLD = 0.15
ZSCORE_ENTRY_LONG_THRESHOLD = -1.5
ZSCORE_ENTRY_SHORT_THRESHOLD = 1.5
MACD_FAST = 12
MACD_SLOW = 26
MACD_SIGNAL_PERIOD = 9

# Backward-compatible aliases
ZSCORE_ENTRY_THRESHOLD = ZSCORE_ENTRY_LONG_THRESHOLD
MACD_SIGNAL = MACD_SIGNAL_PERIOD
