"""
Production Playbook generated by Research OS V3.
Generated at: 2026-07-05T13:12:42.012389
Asset: BTC
Strategy: macd_trend_continuation
"""

class MacdTrendContinuationPlaybook:
    def __init__(self):
        self.symbol = "BTC"
        # Strategy Parameters
        self.fast_period = 12
        self.slow_period = 26
        self.signal_period = 9
        self.min_confidence = 0.65

        # Risk and Gating Limits
        self.max_leverage = 2.0
        self.max_exposure_usd = 5000.0
        self.stop_loss_pct = 0.015
        self.take_profit_pct = 0.03

    def evaluate(self, bars, factors, indicators) -> int:
        """
        Evaluate real-time signals.
        Returns:
            1  for BUY/LONG
            -1 for SELL/SHORT
            0  for NEUTRAL
        """
        macd = indicators.get("MACD")
        macd_sig = indicators.get("MACD_signal")
        if macd is None or macd_sig is None:
            return 0
            
        if macd > macd_sig:
            return 1
        elif macd < macd_sig:
            return -1
        return 0
